### ISSUE TITLE
compatible on qgis 3

### ISSUE THREAD

**Issue by christophemm** [3liz/QgisDynamicLayersPlugin#3]
Hello,
the Dynamic Layers plugin is not compatible on qgis 3.
Has it been replaced by something else ?
Is there an update?
Thank you 
Christophe

**Comment by Gustry** [comment]
The plugin is currently being ported to QGIS 3, see latest commits https://github.com/3liz/QgisDynamicLayersPlugin/commits/master/

A new release will be done soon
